before_script:
  - mysql -e 'create database activeuuid_test;'
  - psql -c 'create database activeuuid_test;' -U postgres

rvm:
  - 2.3.6
  - 2.4.3
  - jruby-9.1.15.0

gemfile:
  - Gemfile
  - gemfiles/Rails-4_0.gemfile
  - gemfiles/Rails-4_1.gemfile
  - gemfiles/Rails-4_2.gemfile
  - gemfiles/Rails-5_0.gemfile
  - gemfiles/Rails-5_1.gemfile
  - gemfiles/Rails-head.gemfile

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

matrix:
  allow_failures:
    - gemfile: gemfiles/Rails-head.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: Gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/Rails-4_0.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/Rails-4_1.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/Rails-4_2.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/Rails-5_0.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/Rails-5_1.gemfile
  exclude:
    - rvm: 2.4.3
      gemfile: gemfiles/Rails-4_0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/Rails-4_1.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/Rails-4_2.gemfile
